/**
 * paymentExportPdf.ts — Renders a printable PDF payment summary.
 *
 * Follows the same "print to PDF" flow used by `ReceiptPDF` / `InvoicePDF`:
 * the summary is rendered as a self-contained HTML document in a new window
 * and the browser's print dialog produces the PDF. Colour tokens come from
 * `src/lib/pdfTheme.ts` so the export stays consistent with the rest of the
 * PDF pipeline.
 */

import type { Payment } from "@stellar-split/sdk";
import { formatAmount } from "@stellar-split/sdk";
import { getPdfTheme } from "@/lib/pdfTheme";

type PaymentWithMeta = Payment & { timestamp?: number; txHash?: string };

/** Escape untrusted text before interpolating it into the HTML document. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Format a payment timestamp (seconds or milliseconds) as an ISO-8601 date. */
function formatTimestamp(timestamp: number | undefined): string {
  if (!timestamp) return "";
  const ms = timestamp < 10000000000 ? timestamp * 1000 : timestamp;
  return new Date(ms).toISOString();
}

/** Sum payment amounts when the SDK exposes them as bigints. */
function sumAmounts(payments: PaymentWithMeta[]): bigint {
  return payments.reduce<bigint>((sum, payment) => {
    return sum + (typeof payment.amount === "bigint" ? payment.amount : 0n);
  }, 0n);
}

/**
 * Build a printable payment-summary HTML document for an invoice.
 * Includes the invoice number, per-payment amounts, payer addresses and
 * transaction hashes, plus a totals row.
 */
export function buildPaymentSummaryHtml(
  invoiceId: string,
  payments: PaymentWithMeta[],
  preferDark = false,
): string {
  const theme = getPdfTheme(preferDark);
  const total = sumAmounts(payments);

  const rows = payments
    .map((payment) => {
      const hash = payment.txHash ? escapeHtml(payment.txHash) : "—";
      return `      <tr>
        <td>${escapeHtml(payment.payer)}</td>
        <td class="amount">${escapeHtml(formatAmount(payment.amount))} USDC</td>
        <td>${escapeHtml(formatTimestamp(payment.timestamp)) || "—"}</td>
        <td class="hash">${hash}</td>
      </tr>`;
    })
    .join("\n");

  const totalRow =
    total > 0n
      ? `      <tr class="total-row">
        <td colspan="3">Total (${payments.length} payment${payments.length === 1 ? "" : "s"})</td>
        <td class="amount">${escapeHtml(formatAmount(total))} USDC</td>
      </tr>`
      : "";

  const emptyRow = `      <tr><td colspan="4" class="empty">No payments to export.</td></tr>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>StellarSplit Payment Summary — Invoice ${escapeHtml(invoiceId)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 820px; margin: 40px auto; color: ${theme.text}; background: ${theme.background}; font-size: 13px; line-height: 1.6; }
    h1 { font-size: 22px; margin-bottom: 4px; color: ${theme.text}; }
    .subtitle { color: ${theme.mutedText}; margin-bottom: 28px; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    thead th { text-align: left; padding: 8px; background: ${theme.surface}; color: ${theme.mutedText}; border-bottom: 2px solid ${theme.border}; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
    tbody td { padding: 8px; border-bottom: 1px solid ${theme.border}; vertical-align: top; word-break: break-all; }
    tbody tr:nth-child(even) td { background: ${theme.surface}; }
    .amount { white-space: nowrap; font-variant-numeric: tabular-nums; }
    .hash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; }
    .total-row td { font-weight: 700; border-top: 2px solid ${theme.accent}; border-bottom: none; }
    .empty { text-align: center; color: ${theme.mutedText}; padding: 24px 0; }
    a { color: ${theme.accent}; }
    .footer { margin-top: 32px; font-size: 11px; color: ${theme.mutedText}; border-top: 1px solid ${theme.border}; padding-top: 12px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>✦ StellarSplit</h1>
  <p class="subtitle">Payment Summary — Invoice #${escapeHtml(invoiceId)}</p>
  <table>
    <thead>
      <tr>
        <th>Recipient Address</th>
        <th>Amount</th>
        <th>Timestamp</th>
        <th>Transaction Hash</th>
      </tr>
    </thead>
    <tbody>
${payments.length > 0 ? rows : emptyRow}
${totalRow}
    </tbody>
  </table>
  <div class="footer">Generated by StellarSplit &mdash; On-chain invoice splitting on Stellar</div>
  <script>window.onload = () => { window.print(); };<\/script>
</body>
</html>`;
}

/** Filename (without download path) for the PDF payment summary. */
export function generatePaymentSummaryFilename(invoiceId: string): string {
  const date = new Date().toISOString().split("T")[0];
  return `payments-invoice-${invoiceId}-${date}.pdf`;
}

/** Open the summary document and trigger the browser's print/PDF dialog. */
export function downloadPaymentSummaryPDF(html: string): void {
  if (typeof window === "undefined") return;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");

  if (win) {
    win.onafterprint = () => {
      URL.revokeObjectURL(url);
      win.close();
    };
  } else {
    URL.revokeObjectURL(url);
  }
}
