"use client";

import { formatAmount } from "@stellar-split/sdk";

const STELLAR_EXPERT_BASE =
  process.env.NEXT_PUBLIC_STELLAR_NETWORK === "mainnet"
    ? "https://stellar.expert/explorer/public/tx"
    : "https://stellar.expert/explorer/testnet/tx";

export interface ReceiptData {
  txHash: string;
  date: Date;
  payerAddress: string;
  invoiceTitle?: string;
  invoiceId: string;
  amountPaid: bigint;
  tipAmount: bigint;
  isDelegated?: boolean;
}

interface Props {
  data: ReceiptData;
}

export default function ReceiptPDF({ data }: Props) {
  const {
    txHash,
    date,
    payerAddress,
    invoiceTitle,
    invoiceId,
    amountPaid,
    tipAmount,
    isDelegated,
  } = data;

  const explorerUrl = `${STELLAR_EXPERT_BASE}/${txHash}`;
  const formattedDate = new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short",
  }).format(date);

  const total = amountPaid + tipAmount;

  const handleDownload = () => {
    // Build a printable HTML receipt in a new window and trigger print-to-PDF
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>StellarSplit Receipt — ${txHash}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 600px; margin: 40px auto; color: #111; font-size: 14px; line-height: 1.6; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    .subtitle { color: #666; margin-bottom: 28px; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { text-align: left; padding: 8px 12px 8px 0; font-weight: 600; width: 180px; color: #444; border-bottom: 1px solid #eee; }
    td { padding: 8px 0; border-bottom: 1px solid #eee; word-break: break-all; }
    .total-row th, .total-row td { border-bottom: 2px solid #111; font-weight: 700; font-size: 15px; }
    a { color: #4f46e5; }
    .footer { margin-top: 32px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 12px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>✦ StellarSplit</h1>
  <p class="subtitle">Payment Receipt${isDelegated ? " (Delegated Payment)" : ""}</p>
  <table>
    <tbody>
      <tr><th>Date</th><td>${formattedDate}</td></tr>
      <tr><th>Invoice</th><td>${invoiceTitle ? invoiceTitle + " " : ""}#${invoiceId}</td></tr>
      <tr><th>Payer Address</th><td>${payerAddress}</td></tr>
      <tr><th>Amount Paid</th><td>${formatAmount(amountPaid)} USDC</td></tr>
      ${tipAmount > 0n ? `<tr><th>Tip</th><td>${formatAmount(tipAmount)} USDC</td></tr>` : ""}
      <tr class="total-row"><th>Total</th><td>${formatAmount(total)} USDC</td></tr>
      <tr><th>Transaction Hash</th><td>${txHash}</td></tr>
      <tr><th>Stellar Expert</th><td><a href="${explorerUrl}">${explorerUrl}</a></td></tr>
    </tbody>
  </table>
  <div class="footer">Generated by StellarSplit &mdash; On-chain invoice splitting on Stellar</div>
  <script>window.onload = () => { window.print(); };<\/script>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onafterprint = () => {
        URL.revokeObjectURL(url);
        win.close();
      };
    }
  };

  return (
    <button
      type="button"
      onClick={handleDownload}
      className="w-full px-4 py-3 rounded-lg bg-indigo-700 hover:bg-indigo-600 text-sm font-semibold transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
    >
      ↓ Download Receipt (PDF)
    </button>
  );
}
